services:
  test-db:
    image: postgres:16
    container_name: test-db
    ports:
      - "9000:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
  one-fit-redis:
    container_name: one-fit-redis
    image: redis:7.2.4
    ports:
      - "9001:6379"