spring:
  data:
    redis:
      url: jdbc:redis://localhost:9001
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
security:
  token:
    expiration: 86400
    secret: ZFwrxIeSMF3oKmMtUq8wCgfDVRnte68J5cRG7aE7eG6nLe2miQyM4We7J7yzME7w
one-fit:
  otp:
    retry-wait-time: 5
    retry-count: 3
    time-to-live: 60
  notification:
    sms:
      eskiz: add your token
  course:
    day:
      duration: 3